##########################################
#        Statistics Configuration        #
##########################################

settings:
  defaultGroup: Silver

groups:
  Silver:
    requiredHours: 0
    requiredXp: 0
  Topaz:
    requiredHours: 15
    requiredXp: 0
  Sapphire:
    requiredHours: 40
    requiredXp: 0
  Ruby:
    requiredHours: 100
    requiredXp: 0
  Emerald:
    requiredHours: 300
    requiredXp: 0
  Diamond:
    requiredHours: 100
    requiredXp: 0